services:
  # 1. Database: Standard PostgreSQL container
  db:
    image: postgres:15-alpine
    container_name: fraud_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists your 'Incident Log'

  # 2. Backend: FastAPI + Isolation Forest
  backend:
    build:
      context: ./backend # Looks inside your 'backend' folder
      dockerfile: Dockerfile
    container_name: fraud_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fraud_db
    depends_on:
      - db
    volumes:
      # Mounts the backend folder so code changes sync immediately (Development only)
      - ./backend:/app

  # 3. Frontend: React/Vite served via Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraud_frontend
    ports:
      - "80:80" # Access the UI at http://localhost
    depends_on:
      - backend

volumes:
  postgres_data:
